//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BilgeAdam.Data.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basket
    {
        public int BasketId { get; set; }
        public int UserId { get; set; }
        public int ProductId { get; set; }
        public int BasketCount { get; set; }
        public int BasketPrice { get; set; }
        public System.DateTime BasketDate { get; set; }
        public int IsDelete { get; set; }
        public int OrderAmount { get; set; }
    }
}
