//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BilgeAdam.Data.Entitiy
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BilgeAdamEntities : DbContext
    {
        public BilgeAdamEntities()
            : base("name=BilgeAdamEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tts_brand> tts_brand { get; set; }
        public virtual DbSet<tts_custumer> tts_custumer { get; set; }
        public virtual DbSet<tts_device> tts_device { get; set; }
        public virtual DbSet<tts_model> tts_model { get; set; }
        public virtual DbSet<tts_user> tts_user { get; set; }
    }
}
