//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BilgeAdam.Data.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int OrderId { get; set; }
        public int UserId { get; set; }
        public System.DateTime ProductId { get; set; }
        public int ProductPrice { get; set; }
        public int ProductCount { get; set; }
        public int OrderAmount { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int IsDelete { get; set; }
    }
}
