//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BilgeAdam.Data.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class tts_user
    {
        public string USER_NAME { get; set; }
        public int ID { get; set; }
        public string PASSWORD { get; set; }
    }
}
